language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn prod
deploy:
  provider: pages:git
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  fqdn: danmdesigns.com
  on:
    branch: master
install:
  - yarn
