import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Daniel Meyer</title>
      </head>
      <body className={inter.className}>
        <Providers>
          <div className="flex justify-center">
            <div className="max-w-5xl">
              <NavBar />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
